apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
      targetPort: 8080